//@ts-nocheck
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@splidejs/splide/dist/css/splide.min.css";
import "react-quill/dist/quill.snow.css";
import QueryProvider from "./QueryProvider";
import ContextProvider from "./ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <ContextProvider>{children}</ContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
